### ISSUE TITLE
should not throw Exception "store.reflect(currentMaterialList) returned previousMaterialList of size == 0. currentMaterialList = CURA/20221212_165311"

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/inspectus4katalon-sample-project#8]
I deleted the `store` directory and the `store-backup` directory. I ran the Test Case `CURA/main`. Then I got the following error.

```
2022-12-12 16:53:47.826 INFO  c.k.katalon.core.main.TestCaseExecutor   - --------------------
step2_materialize finished
2022-12-12 16:53:47.860 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/CURA/main FAILED.
Reason:
com.kazurayam.inspectus.core.InspectusException: com.kazurayam.materialstore.core.filesystem.MaterialstoreException: store.reflect(currentMaterialList) returned previousMaterialList of size == 0. currentMaterialList = CURA/20221212_165311
	at com.kazurayam.inspectus.core.internal.ChronosDiff.step3_reduceChronos(ChronosDiff.java:86)
	at com.kazurayam.inspectus.core.internal.ChronosDiff.process(ChronosDiff.java:28)
	at com.kazurayam.inspectus.core.Inspectus.execute(Inspectus.java:8)
	at com.kazurayam.inspectus.core.Inspectus$execute.call(Unknown Source)
	at main.run(main:38)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:445)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:436)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:415)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:407)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:284)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:142)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:133)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1670831587859.run(TempTestCase1670831587859.groovy:25)
Caused by: com.kazurayam.materialstore.core.filesystem.MaterialstoreException: store.reflect(currentMaterialList) returned previousMaterialList of size == 0. currentMaterialList = CURA/20221212_165311
	at com.kazurayam.materialstore.base.reduce.Reducer.chronos(Reducer.java:72)
	at com.kazurayam.materialstore.base.reduce.Reducer.chronos(Reducer.java:44)
	at com.kazurayam.materialstore.base.reduce.Reducer.chronos(Reducer.java:24)
	at com.kazurayam.inspectus.core.internal.ChronosDiff.step3_reduceChronos(ChronosDiff.java:68)
	at com.kazurayam.inspectus.core.internal.ChronosDiff.process(ChronosDiff.java:28)
	at com.kazurayam.inspectus.core.Inspectus.execute(Inspectus.java:8)
	at com.kazurayam.inspectus.core.Inspectus$execute.call(Unknown Source)
	at Script1667709715867.run(Script1667709715867.groovy:38)
	... 11 more

2022-12-12 16:53:47.870 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/CURA/main FAILED.
Reason:
com.kazurayam.inspectus.core.InspectusException: com.kazurayam.materialstore.core.filesystem.MaterialstoreException: store.reflect(currentMaterialList) returned previousMaterialList of size == 0. currentMaterialList = CURA/20221212_165311
	at com.kazurayam.inspectus.core.internal.ChronosDiff.step3_reduceChronos(ChronosDiff.java:86)
	at com.kazurayam.inspectus.core.internal.ChronosDiff.process(ChronosDiff.java:28)
	at com.kazurayam.inspectus.core.Inspectus.execute(Inspectus.java:8)
	at com.kazurayam.inspectus.core.Inspectus$execute.call(Unknown Source)
	at main.run(main:38)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:445)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:436)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:415)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:407)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:284)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:142)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:133)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1670831587859.run(TempTestCase1670831587859.groovy:25)
Caused by: com.kazurayam.materialstore.core.filesystem.MaterialstoreException: store.reflect(currentMaterialList) returned previousMaterialList of size == 0. currentMaterialList = CURA/20221212_165311
	at com.kazurayam.materialstore.base.reduce.Reducer.chronos(Reducer.java:72)
	at com.kazurayam.materialstore.base.reduce.Reducer.chronos(Reducer.java:44)
	at com.kazurayam.materialstore.base.reduce.Reducer.chronos(Reducer.java:24)
	at com.kazurayam.inspectus.core.internal.ChronosDiff.step3_reduceChronos(ChronosDiff.java:68)
	... 15 more

2022-12-12 16:53:47.879 INFO  c.k.katalon.core.main.TestCaseExecutor   - END Test Cases/CURA/main

```

I know why this error occurs. It is because there is no **previous record**.

When the `store` and `store-backup` is absent, this error will occur.

It is too noisy to throw an Exception and to print verbose StackTrace prints.

I should make it more calm.

No StackTrace should be printed.

Should just say "no previous record, so please try again".

**Comment by kazurayam** [comment]
A fix was made in the materialstore project:

https://github.com/kazurayam/materialstore/issues/389

**Comment by kazurayam** [comment]
Fixed at https://github.com/kazurayam/inspectus4katalon-sample-project/releases/tag/0.3.1

Without the "store" and "store-backup" directory, "Test Cases/CURA/main" no more fails. It silently passes.

Will will find the a set of images previous + diff + current.

A text "Not found" is displayed as the "previous" image:
 
<img width="1552" alt="スクリーンショット 2022-12-12 21 49 12" src="https://user-images.githubusercontent.com/4467417/207061225-bf8f7a2b-ed8a-44f5-98ae-752f8f54f1a6.png">

The current image is as usual.

<img width="1552" alt="スクリーンショット 2022-12-12 21 49 02" src="https://user-images.githubusercontent.com/4467417/207060536-bc72e8f2-01f3-422a-a3cf-24a783188487.png">
